name: Generate ASCII Workflow

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install -y cowsay

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Upload Dragon text file
          uses: actions/upload-artifact@v4.3.4
          with:
            name: dragon-text-file
            path: ./dragon.txt

    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4.1.8
          with:
            name: dragon-text-file

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        needs: [test_job_2]
        steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
          with:
            name: dragon-text-file

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying...